### ISSUE TITLE
Channel deinter/splitting is slow?

### ISSUE THREAD

**Issue by atoav** [iluvcapra/bwavfile#13]
I tried the [wave-deinter example](https://github.com/iluvcapra/bwavfile/blob/master/examples/wave-deinter.rs) and while it worked, I found it to be quite slow compared to existing solutions (I tried with a 10-Channel 32-Bit wav with 540 MB of file size)

I managed to speed things up a little by moving from this:

1. iterating over channels
2. reading the input frames for each
3. writing the appropriate channel to the output

to that:

1. creating output files and readers for each output channel
2. reading the input frames once
3. writing the appropriate sample to each output writer

Additionally I could speed up by using `rayon::par_iter_mut` to write the outputs.

The result is still *magnitudes* slower than splitting the same wav file using sox or ffmpeg. I am not to familiar with the underlying implementation of bwavfile, but I suspect there is potential for optimization?

**Comment by iluvcapra** [comment]
It's been a problem I've been aware of for some time, this was my first library in Rust to kinda kick the tires. I haven't looked at it in a while and I never got far with the code profiling; my guess is that reading the audio sample-by-sample is quite slow and using a buffered reader and writer doesn't make it much faster.
